#%RAML 1.0 NamedExample
{
  "reportDetails": [
    {
      "employeeName": "Miller, Chris",
      "reportId": "35FE2wsdADB4954FCA90CD",
      "reportName": "Quaterly Meeting",
      "reportDate": "2022-01-12"
    }
  ]
}